version: '3'
services:
  hazelcast:
    image: hazelcast/hazelcast
    expose:
      - '5701'
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  thorntail:
    build: .
    depends_on:
      - hazelcast
      - postgres
    ports:
      - '8079-8080:8080'
